import { FlatList, ScrollView, StyleSheet, TouchableOpacity, View, Text } from 'react-native';
import { FAB, Searchbar } from 'react-native-paper';
import { useNavigation } from '@react-navigation/native';
import { EstadoCarregando, EstadoErro, EstadoVazio, TopoTela } from '@shared/components';
import { espaco, raio, semantica, tipografia } from '@shared/theme';
import { CartaoTreinamento } from '../components/CartaoTreinamento';
import { FILTROS_STATUS, useTreinamentos } from '../hooks/useTreinamentos';

export function TreinamentosScreen(){const nav=useNavigation<any>();const x=useTreinamentos();return <View style={e.tela}><TopoTela titulo="Treinamentos" subtitulo={`${x.treinamentos.length} registros`}/><View style={e.top}><Searchbar placeholder="Buscar por título..." value={x.busca} onChangeText={x.setBusca} style={e.busca}/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={e.filtros}>{FILTROS_STATUS.map(f=><TouchableOpacity key={f.valor} onPress={()=>x.setStatus(f.valor)} style={[e.filtro,x.status===f.valor&&e.filtroAtivo]}><Text style={[e.filtroTxt,x.status===f.valor&&e.filtroTxtAtivo]}>{f.rotulo}</Text></TouchableOpacity>)}</ScrollView></View>{x.carregando?<EstadoCarregando mensagem="Carregando treinamentos..."/>:x.erro?<EstadoErro erro={x.erro} aoTentarNovamente={x.recarregar}/>:<FlatList data={x.treinamentos} keyExtractor={i=>String(i.id)} contentContainerStyle={e.lista} ItemSeparatorComponent={()=> <View style={{height:espaco.sm}}/>} refreshing={x.atualizando} onRefresh={x.recarregar} renderItem={({item})=><CartaoTreinamento treinamento={item} aoAbrir={id=>nav.navigate('TreinamentoDetalhe',{id})}/>} ListEmptyComponent={<EstadoVazio titulo="Nenhum treinamento encontrado" descricao="Ajuste os filtros ou crie um novo treinamento."/>}/>}<FAB icon="plus" style={e.fab} onPress={()=>nav.navigate('TreinamentoForm')}/></View>}
const e=StyleSheet.create({tela:{flex:1,backgroundColor:semantica.fundo},top:{padding:espaco.md,paddingBottom:espaco.xs},busca:{backgroundColor:semantica.fundoElevado,borderRadius:raio.medio},filtros:{gap:espaco.xs,paddingTop:espaco.sm,paddingBottom:espaco.xs},filtro:{paddingHorizontal:12,paddingVertical:7,borderRadius:raio.medio,backgroundColor:semantica.fundoElevado,borderWidth:1,borderColor:semantica.borda},filtroAtivo:{backgroundColor:semantica.primario,borderColor:semantica.primario},filtroTxt:{...tipografia.apoio,fontSize:11,color:semantica.textoSecundario},filtroTxtAtivo:{color:'#FFF'},lista:{padding:espaco.md,paddingTop:espaco.xs,paddingBottom:100,flexGrow:1},fab:{position:'absolute',right:espaco.md,bottom:espaco.md,backgroundColor:semantica.primario}});
