import { useEffect,useState } from 'react';
import { KeyboardAvoidingView,Platform,ScrollView,StyleSheet,TouchableOpacity,View,Text } from 'react-native';
import { Button,HelperText,TextInput } from 'react-native-paper';
import { RouteProp,useNavigation,useRoute } from '@react-navigation/native';
import { TopoTela } from '@shared/components';
import { espaco,raio,semantica,tipografia } from '@shared/theme';
import { treinamentosService } from '../services/treinamentosService';
import { useSalvarTreinamento } from '../hooks/useSalvarTreinamento';
import type { StatusTreinamento } from '../types';
type R=RouteProp<{TreinamentoForm:{id?:number}},'TreinamentoForm'>;
const status:{v:StatusTreinamento;l:string}[]=[{v:'pendente',l:'Pendente'},{v:'em_andamento',l:'Em andamento'},{v:'concluido',l:'Concluído'},{v:'cancelado',l:'Cancelado'}];
const paraInput=(iso?:string)=>iso?iso.slice(0,16):'';const paraIso=(v:string)=>{if(!v)return new Date().toISOString();if(v.includes('T')){const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toISOString()}const d=new Date(v+'T08:00:00');return Number.isNaN(d.getTime())?v:d.toISOString()};
export function TreinamentoFormScreen(){const nav=useNavigation<any>();const route=useRoute<R>();const id=route.params?.id;const m=useSalvarTreinamento(id);const [tocado,setTocado]=useState(false);const [v,setV]=useState({titulo:'',descricao:'',cargaHoraria:'8',status:'pendente' as StatusTreinamento,dataInicio:'',dataFim:''});useEffect(()=>{if(id)void treinamentosService.buscarPorId(id).then(t=>setV({titulo:t.titulo,descricao:t.descricao??'',cargaHoraria:String(t.cargaHoraria),status:t.status,dataInicio:paraInput(t.dataInicio),dataFim:paraInput(t.dataFim)}))},[id]);const invalido=!v.titulo.trim()||!v.cargaHoraria.trim();const salvar=async()=>{setTocado(true);if(invalido)return;await m.salvar({titulo:v.titulo.trim(),descricao:v.descricao.trim(),cargaHoraria:Number(v.cargaHoraria)||0,status:v.status,dataInicio:paraIso(v.dataInicio),dataFim:paraIso(v.dataFim||v.dataInicio)});nav.goBack()};return <View style={e.tela}><TopoTela titulo={id?'Editar Treinamento':'Novo Treinamento'} aoVoltar={()=>nav.goBack()}/><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={e.form} keyboardShouldPersistTaps="handled"><TextInput mode="outlined" label="Título *" value={v.titulo} onChangeText={x=>setV({...v,titulo:x})} error={tocado&&!v.titulo.trim()}/><HelperText type="error" visible={tocado&&!v.titulo.trim()}>Título é obrigatório.</HelperText><TextInput mode="outlined" label="Descrição" value={v.descricao} onChangeText={x=>setV({...v,descricao:x})} multiline numberOfLines={4}/><TextInput mode="outlined" label="Carga horária (horas) *" value={v.cargaHoraria} onChangeText={x=>setV({...v,cargaHoraria:x.replace(/\D/g,'')})} keyboardType="number-pad"/><Text style={e.rotulo}>STATUS</Text><View style={e.status}>{status.map(s=><TouchableOpacity key={s.v} onPress={()=>setV({...v,status:s.v})} style={[e.statusBtn,v.status===s.v&&e.statusAtivo]}><Text style={[e.statusTxt,v.status===s.v&&e.statusTxtAtivo]}>{s.l}</Text></TouchableOpacity>)}</View><TextInput mode="outlined" label="Data/hora de início" placeholder="2026-08-20T08:00" value={v.dataInicio} onChangeText={x=>setV({...v,dataInicio:x})}/><TextInput mode="outlined" label="Data/hora de fim" placeholder="2026-08-20T17:00" value={v.dataFim} onChangeText={x=>setV({...v,dataFim:x})}/>{m.erro&&<HelperText type="error" visible>{m.erro.message}</HelperText>}<Button mode="contained" onPress={()=>void salvar()} loading={m.salvando} disabled={m.salvando} contentStyle={{paddingVertical:4}}>{id?'Salvar Alterações':'Criar Treinamento'}</Button></ScrollView></KeyboardAvoidingView></View>}
const e=StyleSheet.create({tela:{flex:1,backgroundColor:semantica.fundo},form:{padding:espaco.md,gap:espaco.xs,paddingBottom:espaco.xxl},rotulo:{...tipografia.etiqueta,color:semantica.textoSecundario,marginTop:espaco.xs},status:{flexDirection:'row',flexWrap:'wrap',gap:espaco.xs},statusBtn:{paddingHorizontal:12,paddingVertical:8,borderRadius:raio.medio,backgroundColor:semantica.fundoElevado,borderWidth:1,borderColor:semantica.borda},statusAtivo:{backgroundColor:semantica.primario,borderColor:semantica.primario},statusTxt:{...tipografia.apoio,fontSize:11,color:semantica.textoSecundario},statusTxtAtivo:{color:'#FFF'}});
