import { useState } from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Icon, IconButton } from 'react-native-paper';
import { RouteProp, useNavigation, useRoute } from '@react-navigation/native';
import { AvatarNome, ChipStatus, EstadoCarregando, EstadoErro, TopoTela } from '@shared/components';
import { cores, espaco, raio, semantica, tipografia } from '@shared/theme';
import { formatarData, formatarPeriodo } from '@shared/utils';
import { useTreinamentoDetalhado } from '../hooks/useTreinamentoDetalhado';
import { useExcluirTreinamento } from '../hooks/useSalvarTreinamento';
import { APRESENTACAO_STATUS } from '../services/treinamentos.mapper';

type Rota = RouteProp<{ TreinamentoDetalhe: { id: number } }, 'TreinamentoDetalhe'>;
type Tab = 'Detalhes' | 'Participantes' | 'Evidências' | 'Assinaturas';
const tabs: Tab[] = ['Detalhes','Participantes','Evidências','Assinaturas'];

export function TreinamentoDetalheScreen(){
  const nav=useNavigation<any>(); const {params}=useRoute<Rota>(); const q=useTreinamentoDetalhado(params.id); const del=useExcluirTreinamento(); const [tab,setTab]=useState<Tab>('Detalhes');
  if(q.carregando)return <EstadoCarregando mensagem="Abrindo treinamento..."/>; if(q.erro)return <EstadoErro erro={q.erro} aoTentarNovamente={q.recarregar}/>; if(!q.detalhe)return null;
  const d=q.detalhe,t=d.treinamento,ap=APRESENTACAO_STATUS[t.status as keyof typeof APRESENTACAO_STATUS];
  const excluir=async()=>{await del.excluir(t.id);nav.goBack()};
  return <View style={e.tela}>
    <TopoTela titulo={t.titulo} aoVoltar={()=>nav.goBack()} acao={<View style={e.acoesTopo}><IconButton icon="pencil-outline" size={20} onPress={()=>nav.navigate('TreinamentoForm',{id:t.id})}/><IconButton icon="trash-can-outline" iconColor={cores.risco} size={20} onPress={()=>void excluir()}/></View>}/>
    <View style={e.statusBar}><ChipStatus rotulo={ap.rotulo} tom={ap.tom}/><Text style={e.statusMeta}>{t.cargaHoraria}h de carga horária</Text></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} style={e.tabs} contentContainerStyle={e.tabsContent}>{tabs.map(x=><TouchableOpacity key={x} onPress={()=>setTab(x)} style={[e.tab,tab===x&&e.tabAtivo]}><Text style={[e.tabTxt,tab===x&&e.tabTxtAtivo]}>{x}</Text>{x==='Participantes'&&<Text style={e.count}>{d.participantes.length}</Text>}{x==='Evidências'&&<Text style={e.count}>{d.evidencias.length}</Text>}{x==='Assinaturas'&&<Text style={e.count}>{d.assinaturas.length}</Text>}</TouchableOpacity>)}</ScrollView>
    <ScrollView style={{flex:1}} contentContainerStyle={e.content} showsVerticalScrollIndicator={false}>
      {tab==='Detalhes'&&<>
        <View style={e.card}><Text style={e.section}>Descrição</Text><Text style={e.corpo}>{t.descricao||'Sem descrição.'}</Text></View>
        <View style={e.card}><View style={e.infoRow}><View style={e.infoIcon}><Icon source="calendar-range" size={19} color={cores.sinal}/></View><View><Text style={e.label}>PERÍODO</Text><Text style={e.valor}>{formatarPeriodo(t.dataInicio,t.dataFim)}</Text></View></View><View style={e.div}/><View style={e.infoRow}><View style={e.infoIcon}><Icon source="clock-outline" size={19} color={cores.sinal}/></View><View><Text style={e.label}>CARGA HORÁRIA</Text><Text style={e.valor}>{t.cargaHoraria} horas</Text></View></View></View>
        <Text style={e.section}>Instrutores</Text>{d.instrutores.length===0?<Text style={e.muted}>Nenhum instrutor vinculado.</Text>:d.instrutores.map(i=><View key={i.id} style={e.person}><AvatarNome nome={i.nome}/><View style={{flex:1}}><Text style={e.personName}>{i.nome}</Text><Text style={e.muted}>{i.especialidade}</Text></View><ChipStatus rotulo={i.interno?'Interno':'Externo'} tom={i.interno?'sucesso':'neutro'}/></View>)}
        <Text style={e.section}>Responsáveis</Text>{d.responsaveis.length===0?<Text style={e.muted}>Nenhum responsável vinculado.</Text>:d.responsaveis.map(r=><View key={r.id} style={e.person}><AvatarNome nome={r.email}/><Text style={e.personName}>{r.email}</Text></View>)}
      </>}
      {tab==='Participantes'&&<>{d.participantes.length===0?<Text style={e.muted}>Nenhum participante inscrito.</Text>:d.participantes.map(p=><View key={p.id} style={e.person}><AvatarNome nome={p.nome||`Funcionário ${p.funcionarioId}`}/><View style={{flex:1}}><Text style={e.personName}>{p.nome||`Funcionário #${p.funcionarioId}`}</Text><Text style={e.muted}>{p.matricula?`Matrícula ${p.matricula} · `:''}Inscrito em {formatarData(p.inscritoEm)}</Text></View><ChipStatus rotulo={p.status} tom={p.status==='aprovado'?'sucesso':p.status==='reprovado'?'perigo':'aviso'}/></View>)}</>}
      {tab==='Evidências'&&<>{d.evidencias.length===0?<Text style={e.muted}>Nenhuma evidência registrada.</Text>:d.evidencias.map(x=><View key={x.id} style={e.file}><View style={e.fileIcon}><Icon source={x.tipo==='foto'?'image-outline':x.tipo==='video'?'video-outline':'file-outline'} size={22} color={cores.ciano}/></View><View style={{flex:1}}><Text style={e.personName}>{x.descricao||x.arquivo||'Evidência'}</Text><Text style={e.muted}>{x.tipo} · {formatarData(x.registradoEm)}</Text><Text style={e.fileName}>{x.arquivo||'arquivo não informado'}</Text></View></View>)}</>}
      {tab==='Assinaturas'&&<>{d.assinaturas.length===0?<Text style={e.muted}>Nenhuma assinatura registrada.</Text>:d.assinaturas.map(x=>{const p=d.participantes.find(p=>p.id===x.treinamentoParticipantesId);return <View key={x.id} style={e.file}><View style={[e.fileIcon,{backgroundColor:cores.ancoradoSuave}]}><Icon source="draw-pen" size={22} color={cores.ancorado}/></View><View style={{flex:1}}><Text style={e.personName}>{p?.nome||`Participante #${x.treinamentoParticipantesId}`}</Text><Text style={e.muted}>{x.tipo.replace(/_/g,' ')} · {x.assinadoEm?new Date(x.assinadoEm).toLocaleString('pt-BR'):'—'}</Text>{!!x.hash&&<Text style={e.hash} numberOfLines={1}>{x.hash}</Text>}</View></View>})}</>}
    </ScrollView>
  </View>
}
const e=StyleSheet.create({tela:{flex:1,backgroundColor:semantica.fundo},acoesTopo:{flexDirection:'row'},statusBar:{backgroundColor:semantica.fundoElevado,borderBottomWidth:1,borderBottomColor:semantica.borda,paddingHorizontal:espaco.md,paddingVertical:espaco.sm,flexDirection:'row',alignItems:'center',gap:espaco.sm},statusMeta:{...tipografia.apoio,fontSize:11,color:semantica.textoSecundario},tabs:{maxHeight:48,backgroundColor:semantica.fundoElevado,borderBottomWidth:1,borderBottomColor:semantica.borda},tabsContent:{paddingHorizontal:espaco.xs},tab:{paddingHorizontal:espaco.sm,paddingVertical:13,flexDirection:'row',gap:5,alignItems:'center',borderBottomWidth:2,borderBottomColor:'transparent'},tabAtivo:{borderBottomColor:semantica.primario},tabTxt:{...tipografia.apoio,fontFamily:'IBMPlexSans_600SemiBold',color:semantica.textoSecundario},tabTxtAtivo:{color:semantica.primario},count:{...tipografia.apoio,fontSize:9,color:semantica.textoSecundario,backgroundColor:cores.neve100,paddingHorizontal:5,paddingVertical:1,borderRadius:raio.pilula},content:{padding:espaco.md,gap:espaco.sm,paddingBottom:espaco.xxl},card:{backgroundColor:semantica.fundoElevado,borderWidth:1,borderColor:semantica.borda,borderRadius:raio.grande,padding:espaco.md,gap:espaco.sm},section:{...tipografia.subtitulo,fontSize:14,color:semantica.texto,marginTop:espaco.xs},corpo:{...tipografia.corpo,fontSize:13,color:semantica.textoSecundario},infoRow:{flexDirection:'row',alignItems:'center',gap:espaco.sm},infoIcon:{width:38,height:38,borderRadius:raio.medio,backgroundColor:cores.sinalSuave,alignItems:'center',justifyContent:'center'},label:{...tipografia.etiqueta,fontSize:10,color:semantica.textoSecundario},valor:{...tipografia.corpo,fontSize:13,color:semantica.texto},div:{height:1,backgroundColor:semantica.borda},person:{backgroundColor:semantica.fundoElevado,borderWidth:1,borderColor:semantica.borda,borderRadius:raio.grande,padding:espaco.sm,flexDirection:'row',alignItems:'center',gap:espaco.sm},personName:{...tipografia.subtitulo,fontSize:13,color:semantica.texto},muted:{...tipografia.apoio,fontSize:11,color:semantica.textoSecundario},file:{backgroundColor:semantica.fundoElevado,borderWidth:1,borderColor:semantica.borda,borderRadius:raio.grande,padding:espaco.sm,flexDirection:'row',gap:espaco.sm,alignItems:'center'},fileIcon:{width:42,height:42,borderRadius:raio.medio,backgroundColor:cores.cianoSuave,alignItems:'center',justifyContent:'center'},fileName:{...tipografia.codigo,fontSize:9,color:semantica.textoSecundario,marginTop:3},hash:{...tipografia.codigo,fontSize:9,color:semantica.textoSecundario,marginTop:3}});
