import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { useAppErro } from '@shared/hooks';
import { administracaoService } from '../services/administracaoService';
import type { PerfilInput,UsuarioInput } from '../types';
export const chavesAdmin={usuarios:['admin','usuarios'] as const,perfis:['admin','perfis'] as const,permissoes:['admin','permissoes'] as const,auditoria:['admin','auditoria'] as const,funcionarios:['admin','funcionarios'] as const};
export function useUsuarios(){const qc=useQueryClient();const q=useQuery({queryKey:chavesAdmin.usuarios,queryFn:administracaoService.listarUsuarios});const f=useQuery({queryKey:chavesAdmin.funcionarios,queryFn:administracaoService.listarFuncionarios});const del=useMutation({mutationFn:administracaoService.excluirUsuario,onSuccess:()=>qc.invalidateQueries({queryKey:chavesAdmin.usuarios})});const patch=useMutation({mutationFn:({id,input}:{id:number;input:UsuarioInput})=>administracaoService.salvarUsuario(input,id),onSuccess:()=>qc.invalidateQueries({queryKey:chavesAdmin.usuarios})});return{usuarios:q.data??[],funcionarios:f.data??[],carregando:q.isPending||f.isPending,erro:useAppErro(q.error||f.error),recarregar:q.refetch,excluir:del.mutateAsync,atualizar:patch.mutateAsync}}
export function useSalvarUsuario(id?:number){const qc=useQueryClient();const m=useMutation({mutationFn:(input:UsuarioInput)=>administracaoService.salvarUsuario(input,id),onSuccess:()=>qc.invalidateQueries({queryKey:chavesAdmin.usuarios})});return{salvar:m.mutateAsync,salvando:m.isPending,erro:useAppErro(m.error)}}
export function usePerfis(){const qc=useQueryClient();const q=useQuery({queryKey:chavesAdmin.perfis,queryFn:administracaoService.listarPerfis});const del=useMutation({mutationFn:administracaoService.excluirPerfil,onSuccess:()=>qc.invalidateQueries({queryKey:chavesAdmin.perfis})});return{perfis:q.data??[],carregando:q.isPending,erro:useAppErro(q.error),recarregar:q.refetch,excluir:del.mutateAsync}}
export function useSalvarPerfil(id?:number){const qc=useQueryClient();const m=useMutation({mutationFn:(input:PerfilInput)=>administracaoService.salvarPerfil(input,id),onSuccess:()=>qc.invalidateQueries({queryKey:chavesAdmin.perfis})});return{salvar:m.mutateAsync,salvando:m.isPending,erro:useAppErro(m.error)}}
export function usePermissoes(){const q=useQuery({queryKey:chavesAdmin.permissoes,queryFn:administracaoService.listarPermissoes});return{permissoes:q.data??[],carregando:q.isPending,erro:useAppErro(q.error),recarregar:q.refetch}}
export function useAuditoria(){const q=useQuery({queryKey:chavesAdmin.auditoria,queryFn:administracaoService.listarAuditorias});return{auditorias:q.data??[],carregando:q.isPending,erro:useAppErro(q.error),recarregar:q.refetch}}
