import { useMemo,useState } from 'react';
import { FlatList,StyleSheet,Text,View } from 'react-native';
import { Searchbar } from 'react-native-paper';
import { useNavigation } from '@react-navigation/native';
import { ChipStatus,EstadoCarregando,EstadoErro,TopoTela } from '@shared/components';
import { espaco,raio,semantica,tipografia } from '@shared/theme';
import { usePermissoes } from '../hooks/useAdministracao';
export function PermissoesScreen(){const nav=useNavigation<any>();const x=usePermissoes();const [busca,setBusca]=useState('');const itens=useMemo(()=>x.permissoes.filter(p=>(p.codigo+' '+p.recurso+' '+p.descricao).toLowerCase().includes(busca.toLowerCase())),[x.permissoes,busca]);return <View style={e.tela}><TopoTela titulo="Permissões" subtitulo={`${x.permissoes.length} registros`} aoVoltar={()=>nav.goBack()}/><View style={e.busca}><Searchbar placeholder="Código, recurso ou descrição..." value={busca} onChangeText={setBusca}/></View>{x.carregando?<EstadoCarregando/>:x.erro?<EstadoErro erro={x.erro} aoTentarNovamente={x.recarregar}/>:<FlatList data={itens} keyExtractor={i=>String(i.id)} contentContainerStyle={e.lista} renderItem={({item})=><View style={e.card}><View style={e.top}><ChipStatus rotulo={item.metodo} tom={item.metodo==='GET'?'sucesso':item.metodo==='DELETE'?'perigo':'sinal'}/><Text style={e.codigo}>{item.codigo}</Text>{item.ehPublico&&<ChipStatus rotulo="Público" tom="sucesso"/>}</View><Text style={e.desc}>{item.descricao||'Sem descrição'}</Text><Text style={e.rota}>{item.rotaTemplate}</Text></View>}/>}</View>}
const e=StyleSheet.create({tela:{flex:1,backgroundColor:semantica.fundo},busca:{padding:espaco.md,paddingBottom:espaco.xs},lista:{padding:espaco.md,paddingTop:espaco.xs,paddingBottom:60,gap:espaco.sm},card:{backgroundColor:semantica.fundoElevado,borderRadius:raio.grande,borderWidth:1,borderColor:semantica.borda,padding:espaco.md},top:{flexDirection:'row',alignItems:'center',gap:espaco.xs,flexWrap:'wrap'},codigo:{...tipografia.codigo,fontSize:11,color:semantica.texto,flexShrink:1},desc:{...tipografia.apoio,fontSize:12,color:semantica.textoSecundario,marginTop:espaco.xs},rota:{...tipografia.codigo,fontSize:10,color:semantica.textoSecundario,marginTop:4}});
