import { useEffect,useState } from 'react';
import { ScrollView,StyleSheet,View } from 'react-native';
import { Button,HelperText,Switch,Text,TextInput } from 'react-native-paper';
import { RouteProp,useNavigation,useRoute } from '@react-navigation/native';
import { TopoTela } from '@shared/components';
import { espaco,semantica } from '@shared/theme';
import { administracaoService } from '../services/administracaoService';
import { useSalvarUsuario } from '../hooks/useAdministracao';
type R=RouteProp<{UsuarioForm:{id?:number}},'UsuarioForm'>;
export function UsuarioFormScreen(){const nav=useNavigation<any>();const route=useRoute<R>();const id=route.params?.id;const [v,setV]=useState({email:'',senha:'',funcionarioId:'',ativo:true});const [funcs,setFuncs]=useState<{id:number;nome:string;matricula:string}[]>([]);const m=useSalvarUsuario(id);useEffect(()=>{void administracaoService.listarFuncionarios().then(xs=>setFuncs(xs));if(id)void administracaoService.listarUsuarios().then(xs=>{const u=xs.find(x=>x.id===id);if(u)setV({email:u.email,senha:'',funcionarioId:String(u.funcionarioId??''),ativo:u.ativo})})},[id]);const salvar=async()=>{if(!v.email.trim()||!v.funcionarioId)return;await m.salvar({email:v.email,senha:v.senha||undefined,funcionarioId:Number(v.funcionarioId),ativo:v.ativo,criadoEm:new Date().toISOString()});nav.goBack()};return <View style={e.tela}><TopoTela titulo={id?'Editar Usuário':'Novo Usuário'} aoVoltar={()=>nav.goBack()}/><ScrollView contentContainerStyle={e.form}><TextInput mode="outlined" label="E-mail" value={v.email} onChangeText={x=>setV({...v,email:x})} keyboardType="email-address" autoCapitalize="none"/><TextInput mode="outlined" label={id?'Nova senha (opcional)':'Senha'} value={v.senha} onChangeText={x=>setV({...v,senha:x})} secureTextEntry/><TextInput mode="outlined" label="ID do funcionário" value={v.funcionarioId} onChangeText={x=>setV({...v,funcionarioId:x.replace(/\D/g,'')})} keyboardType="number-pad"/><Text style={e.ajuda}>Funcionários disponíveis: {funcs.map(f=>`${f.id} - ${f.nome}`).join(' · ')}</Text><View style={e.switch}><Text>Usuário ativo</Text><Switch value={v.ativo} onValueChange={x=>setV({...v,ativo:x})}/></View>{m.erro&&<HelperText type="error" visible>{m.erro.message}</HelperText>}<Button mode="contained" onPress={()=>void salvar()} loading={m.salvando}>{id?'Salvar Alterações':'Cadastrar Usuário'}</Button></ScrollView></View>}
const e=StyleSheet.create({tela:{flex:1,backgroundColor:semantica.fundo},form:{padding:espaco.md,gap:espaco.sm},ajuda:{fontSize:11,color:'#64748B'},switch:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}});
