import { FlatList,StyleSheet,Text,TouchableOpacity,View } from 'react-native';
import { FAB,IconButton } from 'react-native-paper';
import { useNavigation } from '@react-navigation/native';
import { AvatarNome,ChipStatus,EstadoCarregando,EstadoErro,TopoTela } from '@shared/components';
import { espaco,raio,semantica,tipografia } from '@shared/theme';
import { formatarData } from '@shared/utils';
import { useUsuarios } from '../hooks/useAdministracao';
export function UsuariosScreen(){const nav=useNavigation<any>();const x=useUsuarios();const nome=(id?:number)=>x.funcionarios.find(f=>f.id===id)?.nome??'Sem funcionário vinculado';return <View style={e.tela}><TopoTela titulo="Usuários" subtitulo={`${x.usuarios.length} cadastrados`} aoVoltar={()=>nav.goBack()}/>{x.carregando?<EstadoCarregando/>:x.erro?<EstadoErro erro={x.erro} aoTentarNovamente={x.recarregar}/>:<FlatList data={x.usuarios} keyExtractor={i=>String(i.id)} contentContainerStyle={e.lista} renderItem={({item})=><View style={e.card}><View style={e.row}><AvatarNome nome={nome(item.funcionarioId)}/><View style={{flex:1}}><Text style={e.nome}>{nome(item.funcionarioId)}</Text><Text style={e.meta}>{item.email}</Text><Text style={e.data}>Criado em {formatarData(item.criadoEm)}</Text></View><ChipStatus rotulo={item.ativo?'Ativo':'Inativo'} tom={item.ativo?'sucesso':'neutro'}/></View><View style={e.acoes}><TouchableOpacity style={e.botao} onPress={()=>void x.atualizar({id:item.id,input:{email:item.email,funcionarioId:item.funcionarioId??0,ativo:!item.ativo,criadoEm:item.criadoEm??new Date().toISOString()}})}><Text style={e.botaoTxt}>{item.ativo?'Desativar':'Ativar'}</Text></TouchableOpacity><IconButton icon="pencil-outline" size={18} onPress={()=>nav.navigate('UsuarioForm',{id:item.id})}/><IconButton icon="trash-can-outline" iconColor="#DC2626" size={18} onPress={()=>void x.excluir(item.id)}/></View></View>}/>}<FAB icon="plus" style={e.fab} onPress={()=>nav.navigate('UsuarioForm')}/></View>}
const e=StyleSheet.create({tela:{flex:1,backgroundColor:semantica.fundo},lista:{padding:espaco.md,paddingBottom:100,gap:espaco.sm},card:{backgroundColor:semantica.fundoElevado,borderRadius:raio.grande,borderWidth:1,borderColor:semantica.borda},row:{flexDirection:'row',alignItems:'center',gap:espaco.sm,padding:espaco.md},nome:{...tipografia.subtitulo,fontSize:14,color:semantica.texto},meta:{...tipografia.apoio,fontSize:12,color:semantica.textoSecundario},data:{...tipografia.apoio,fontSize:10,color:semantica.textoSecundario,marginTop:3},acoes:{flexDirection:'row',alignItems:'center',justifyContent:'flex-end',borderTopWidth:1,borderTopColor:semantica.borda,paddingHorizontal:espaco.xs},botao:{paddingHorizontal:10,paddingVertical:6,backgroundColor:'#F1F5F9',borderRadius:raio.pequeno},botaoTxt:{...tipografia.apoio,fontSize:11,color:semantica.textoSecundario},fab:{position:'absolute',right:espaco.md,bottom:espaco.md,backgroundColor:semantica.primario}});
