import { useEffect,useState } from 'react';
import { KeyboardAvoidingView,Platform,ScrollView,StyleSheet,View } from 'react-native';
import { Button,HelperText,Switch,Text,TextInput } from 'react-native-paper';
import { RouteProp,useNavigation,useRoute } from '@react-navigation/native';
import { TopoTela } from '@shared/components';
import { espaco,semantica } from '@shared/theme';
import { instrutoresService } from '../services/instrutoresService';
import { useSalvarInstrutor } from '../hooks/useInstrutores';
type R=RouteProp<{InstrutorForm:{id?:number}},'InstrutorForm'>;
export function InstrutorFormScreen(){const nav=useNavigation<any>();const route=useRoute<R>();const id=route.params?.id;const [v,setV]=useState({nome:'',especialidade:'',registro:'',email:'',interno:true});const [t,setT]=useState(false);const m=useSalvarInstrutor(id);useEffect(()=>{if(id)void instrutoresService.buscar(id).then(i=>setV({nome:i.nome,especialidade:i.especialidade,registro:i.registro??'',email:i.email??'',interno:i.interno}))},[id]);const invalid=!v.nome.trim()||!v.especialidade.trim();const salvar=async()=>{setT(true);if(invalid)return;await m.salvar(v);nav.goBack()};return <View style={e.tela}><TopoTela titulo={id?'Editar Instrutor':'Novo Instrutor'} aoVoltar={()=>nav.goBack()}/><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={e.form}>{([['nome','Nome completo'],['especialidade','Especialidade'],['registro','Registro profissional'],['email','E-mail']] as const).map(([k,l])=><View key={k}><TextInput mode="outlined" label={l} value={v[k]} onChangeText={x=>setV({...v,[k]:x})} error={t&&(k==='nome'||k==='especialidade')&&!v[k].trim()} keyboardType={k==='email'?'email-address':'default'}/>{(k==='nome'||k==='especialidade')&&<HelperText type="error" visible={t&&!v[k].trim()}>{l} é obrigatório.</HelperText>}</View>)}<View style={e.switch}><Text>Instrutor interno</Text><Switch value={v.interno} onValueChange={x=>setV({...v,interno:x})}/></View>{m.erro&&<HelperText type="error" visible>{m.erro.message}</HelperText>}<Button mode="contained" onPress={()=>void salvar()} loading={m.salvando}>{id?'Salvar Alterações':'Cadastrar Instrutor'}</Button></ScrollView></KeyboardAvoidingView></View>}
const e=StyleSheet.create({tela:{flex:1,backgroundColor:semantica.fundo},form:{padding:espaco.md,gap:espaco.xs,paddingBottom:espaco.xxl},switch:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingVertical:espaco.sm}});
