import { StyleSheet,Text,TouchableOpacity,View } from 'react-native';
import { IconButton } from 'react-native-paper';
import { RouteProp,useNavigation,useRoute } from '@react-navigation/native';
import { AvatarNome,ChipStatus,EstadoCarregando,EstadoErro,TelaBase,TopoTela } from '@shared/components';
import { espaco,raio,semantica,tipografia } from '@shared/theme';
import { formatarData } from '@shared/utils';
import { useInstrutorDetalhe } from '../hooks/useInstrutores';
type R=RouteProp<{InstrutorDetalhe:{id:number}},'InstrutorDetalhe'>;
export function InstrutorDetalheScreen(){const nav=useNavigation<any>();const {params}=useRoute<R>();const q=useInstrutorDetalhe(params.id);if(q.carregando)return<EstadoCarregando/>;if(q.erro)return<EstadoErro erro={q.erro} aoTentarNovamente={q.recarregar}/>;if(!q.detalhe)return null;const {instrutor:i,treinamentos}=q.detalhe;return <View style={e.tela}><TopoTela titulo="Instrutor" aoVoltar={()=>nav.goBack()} acao={<IconButton icon="pencil-outline" onPress={()=>nav.navigate('InstrutorForm',{id:i.id})}/>}/><TelaBase rolavel estilo={e.content}><View style={e.perfil}><AvatarNome nome={i.nome} tamanho={68}/><View style={{flex:1}}><Text style={e.nome}>{i.nome}</Text><Text style={e.meta}>{i.especialidade}</Text><ChipStatus rotulo={i.interno?'Interno':'Externo'} tom={i.interno?'sucesso':'neutro'}/></View></View><View style={e.card}><Text style={e.label}>Registro</Text><Text style={e.valor}>{i.registro||'Não informado'}</Text><Text style={e.label}>E-mail</Text><Text style={e.valor}>{i.email||'Não informado'}</Text></View><Text style={e.secao}>Treinamentos vinculados</Text>{treinamentos.length===0?<Text style={e.meta}>Nenhum treinamento vinculado.</Text>:treinamentos.map(t=><TouchableOpacity key={t.id} style={e.item} onPress={()=>nav.navigate('Treinamentos',{screen:'TreinamentoDetalhe',params:{id:t.id}})}><View style={{flex:1}}><Text style={e.itemT}>{t.titulo}</Text><Text style={e.meta}>{formatarData(t.dataInicio)} · {t.cargaHoraria||0}h</Text></View><ChipStatus rotulo={t.status||'—'} tom={t.status==='concluido'?'sucesso':'sinal'}/></TouchableOpacity>)}</TelaBase></View>}
const e=StyleSheet.create({tela:{flex:1,backgroundColor:semantica.fundo},content:{gap:espaco.md},perfil:{backgroundColor:semantica.fundoElevado,borderRadius:raio.grande,borderWidth:1,borderColor:semantica.borda,padding:espaco.md,flexDirection:'row',gap:espaco.md,alignItems:'center'},nome:{...tipografia.titulo,color:semantica.texto},meta:{...tipografia.apoio,color:semantica.textoSecundario,marginVertical:3},card:{backgroundColor:semantica.fundoElevado,borderRadius:raio.grande,borderWidth:1,borderColor:semantica.borda,padding:espaco.md,gap:4},label:{...tipografia.etiqueta,color:semantica.textoSecundario,marginTop:espaco.xs},valor:{...tipografia.corpo,color:semantica.texto},secao:{...tipografia.subtitulo,fontSize:14,color:semantica.texto},item:{backgroundColor:semantica.fundoElevado,borderRadius:raio.grande,borderWidth:1,borderColor:semantica.borda,padding:espaco.sm,flexDirection:'row',alignItems:'center',gap:espaco.sm},itemT:{...tipografia.subtitulo,fontSize:13,color:semantica.texto}});
