import { useMemo,useState } from 'react';
import { FlatList,ScrollView,StyleSheet,Text,TouchableOpacity,View } from 'react-native';
import { Searchbar } from 'react-native-paper';
import { useNavigation } from '@react-navigation/native';
import { EstadoCarregando,EstadoErro,EstadoVazio,TopoTela } from '@shared/components';
import { cores,espaco,raio,semantica,tipografia } from '@shared/theme';
import { CartaoCertificado } from '../components/CartaoCertificado';
import { useCertificados } from '../hooks/useCertificados';
import type { StatusCertificado } from '../types';
const filtros:{v:StatusCertificado|'todos';l:string}[]=[{v:'todos',l:'Todos'},{v:'valido',l:'Válidos'},{v:'expirado',l:'Expirados'},{v:'cancelado',l:'Cancelados'}];
export function CertificadosScreen(){const nav=useNavigation<any>();const x=useCertificados();const [busca,setBusca]=useState('');const [status,setStatus]=useState<StatusCertificado|'todos'>('todos');const itens=useMemo(()=>x.certificados.filter(c=>(!busca||c.numero.toLowerCase().includes(busca.toLowerCase()))&&(status==='todos'||c.status===status)),[x.certificados,busca,status]);return <View style={e.tela}><TopoTela titulo="Certificados" subtitulo={`${x.certificados.length} registros`}/><View style={e.top}>{x.proximosDoVencimento.length>0&&<View style={e.alerta}><Text style={e.alertaT}>⚠️ Certificados próximos do vencimento</Text><Text style={e.alertaM}>{x.proximosDoVencimento.length} certificado(s) vencem em até 60 dias.</Text></View>}<Searchbar placeholder="Buscar por número..." value={busca} onChangeText={setBusca} style={e.busca}/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={e.filtros}>{filtros.map(f=><TouchableOpacity key={f.v} onPress={()=>setStatus(f.v)} style={[e.filtro,status===f.v&&e.filtroAtivo]}><Text style={[e.filtroTxt,status===f.v&&e.filtroTxtAtivo]}>{f.l}</Text></TouchableOpacity>)}</ScrollView></View>{x.carregando?<EstadoCarregando/>:x.erro?<EstadoErro erro={x.erro} aoTentarNovamente={x.recarregar}/>:<FlatList data={itens} keyExtractor={i=>String(i.id)} contentContainerStyle={e.lista} ItemSeparatorComponent={()=> <View style={{height:espaco.sm}}/>} refreshing={x.atualizando} onRefresh={x.recarregar} renderItem={({item})=><CartaoCertificado certificado={item} aoAbrir={id=>nav.navigate('CertificadoDetalhe',{id})}/>} ListEmptyComponent={<EstadoVazio titulo="Nenhum certificado encontrado"/>}/>}</View>}
const e=StyleSheet.create({tela:{flex:1,backgroundColor:semantica.fundo},top:{padding:espaco.md,paddingBottom:espaco.xs,gap:espaco.sm},alerta:{backgroundColor:cores.atencaoSuave,borderWidth:1,borderColor:'#FDE68A',borderRadius:raio.grande,padding:espaco.sm},alertaT:{...tipografia.subtitulo,fontSize:12,color:'#92400E'},alertaM:{...tipografia.apoio,fontSize:10,color:'#A16207',marginTop:2},busca:{backgroundColor:semantica.fundoElevado,borderRadius:raio.medio},filtros:{gap:espaco.xs,paddingBottom:espaco.xs},filtro:{paddingHorizontal:12,paddingVertical:7,borderRadius:raio.medio,backgroundColor:semantica.fundoElevado,borderWidth:1,borderColor:semantica.borda},filtroAtivo:{backgroundColor:semantica.primario,borderColor:semantica.primario},filtroTxt:{...tipografia.apoio,fontSize:11,color:semantica.textoSecundario},filtroTxtAtivo:{color:'#FFF'},lista:{padding:espaco.md,paddingTop:espaco.xs,paddingBottom:60,flexGrow:1}});
