import { StyleSheet,Text,View } from 'react-native';
import { Icon } from 'react-native-paper';
import { RouteProp,useNavigation,useRoute } from '@react-navigation/native';
import { ChipStatus,EstadoCarregando,EstadoErro,TelaBase,TopoTela } from '@shared/components';
import { cores,espaco,raio,semantica,tipografia } from '@shared/theme';
import { formatarData } from '@shared/utils';
import { useCertificadoDetalhado } from '../hooks/useCertificadoDetalhado';
import { APRESENTACAO_STATUS_CERTIFICADO } from '../services/certificados.mapper';
type R=RouteProp<{CertificadoDetalhe:{id:number}},'CertificadoDetalhe'>;
export function CertificadoDetalheScreen(){const nav=useNavigation<any>();const {params}=useRoute<R>();const q=useCertificadoDetalhado(params.id);if(q.carregando)return<EstadoCarregando/>;if(q.erro)return<EstadoErro erro={q.erro} aoTentarNovamente={q.recarregar}/>;if(!q.detalhe)return null;const {certificado:c,funcionario:f,treinamento:t}=q.detalhe;const ap=APRESENTACAO_STATUS_CERTIFICADO[c.status as keyof typeof APRESENTACAO_STATUS_CERTIFICADO];return <View style={e.tela}><TopoTela titulo="Certificado" aoVoltar={()=>nav.goBack()}/><TelaBase rolavel estilo={e.content}><View style={e.hero}><View style={e.medal}><Icon source="medal" size={32} color={cores.atencao}/></View><Text style={e.label}>CERTIFICADO</Text><Text style={e.numero}>{c.numero}</Text><ChipStatus rotulo={ap.rotulo} tom={ap.tom}/></View><View style={e.card}><Text style={e.section}>Participante</Text><Text style={e.valor}>{f?.nome??'Não informado'}</Text><Text style={e.meta}>{f?`Matrícula ${f.matricula}${f.cargo?` · ${f.cargo}`:''}`:'Vínculo não encontrado'}</Text><View style={e.div}/><Text style={e.section}>Treinamento</Text><Text style={e.valor}>{t?.titulo??'Não informado'}</Text><Text style={e.meta}>{t?`${t.cargaHoraria} horas`:'—'}</Text><View style={e.div}/><Text style={e.section}>Vigência</Text><Text style={e.meta}>Emissão: {formatarData(c.dataEmissao)}</Text><Text style={e.meta}>Validade: {formatarData(c.dataValidade)}</Text></View></TelaBase></View>}
const e=StyleSheet.create({tela:{flex:1,backgroundColor:semantica.fundo},content:{gap:espaco.md},hero:{backgroundColor:semantica.fundoElevado,borderWidth:1,borderColor:semantica.borda,borderRadius:raio.extra,padding:espaco.lg,alignItems:'center',gap:espaco.xs},medal:{width:58,height:58,borderRadius:29,backgroundColor:cores.atencaoSuave,alignItems:'center',justifyContent:'center',marginBottom:espaco.xs},label:{...tipografia.etiqueta,color:semantica.textoSecundario},numero:{...tipografia.codigo,fontSize:20,lineHeight:26,color:semantica.texto},card:{backgroundColor:semantica.fundoElevado,borderWidth:1,borderColor:semantica.borda,borderRadius:raio.grande,padding:espaco.md,gap:4},section:{...tipografia.etiqueta,color:semantica.textoSecundario,marginTop:espaco.xs},valor:{...tipografia.subtitulo,fontSize:14,color:semantica.texto},meta:{...tipografia.apoio,fontSize:12,color:semantica.textoSecundario},div:{height:1,backgroundColor:semantica.borda,marginVertical:espaco.sm}});
