import { StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { IconButton } from 'react-native-paper';
import { RouteProp, useNavigation, useRoute } from '@react-navigation/native';
import { AvatarNome, ChipStatus, EstadoCarregando, EstadoErro, TelaBase, TopoTela } from '@shared/components';
import { cores, espaco, raio, semantica, tipografia } from '@shared/theme';
import { formatarData } from '@shared/utils';
import { useFuncionarioDetalhe } from '../hooks/useFuncionarios';

type R=RouteProp<{FuncionarioDetalhe:{id:number}},'FuncionarioDetalhe'>;
const tom=(s:string)=>s==='aprovado'||s==='valido'?'sucesso':s==='reprovado'||s==='expirado'?'perigo':'aviso';
export function FuncionarioDetalheScreen(){const nav=useNavigation<any>();const {params}=useRoute<R>();const {detalhe,carregando,erro,recarregar}=useFuncionarioDetalhe(params.id);if(carregando)return <EstadoCarregando/>;if(erro)return <EstadoErro erro={erro} aoTentarNovamente={recarregar}/>;if(!detalhe)return null;const {funcionario:f,participacoes,treinamentos,certificados}=detalhe;return <View style={e.tela}><TopoTela titulo="Funcionário" aoVoltar={()=>nav.goBack()} acao={<IconButton icon="pencil-outline" onPress={()=>nav.navigate('FuncionarioForm',{id:f.id})}/>}/><TelaBase rolavel estilo={e.conteudo}>
<View style={e.perfil}><AvatarNome nome={f.nome} tamanho={68}/><View style={{flex:1}}><Text style={e.nome}>{f.nome}</Text><Text style={e.meta}>{f.cargo||'Cargo não informado'}</Text><View style={e.chips}><Text style={e.chip}>{f.setor||'Sem setor'}</Text><Text style={e.codigo}>{f.matricula}</Text></View></View></View>
<View style={e.grade}>{[{l:'Treinamentos',v:treinamentos.length},{l:'Aprovados',v:participacoes.filter(p=>p.status==='aprovado').length},{l:'Certificados',v:certificados.length}].map(x=><View key={x.l} style={e.stat}><Text style={e.statN}>{x.v}</Text><Text style={e.statL}>{x.l}</Text></View>)}</View>
<Text style={e.secao}>Histórico de Treinamentos</Text>{treinamentos.map(t=>{const p=participacoes.find(x=>x.treinamentoId===t.id);return <TouchableOpacity key={t.id} style={e.item} onPress={()=>nav.navigate('Treinamentos',{screen:'TreinamentoDetalhe',params:{id:t.id}})}><View style={{flex:1}}><Text style={e.itemT}>{t.titulo}</Text><Text style={e.itemM}>{t.cargaHoraria||0}h · {formatarData(t.dataInicio)}</Text></View>{p&&<ChipStatus rotulo={p.status} tom={tom(p.status) as any}/>}</TouchableOpacity>})}
{certificados.length>0&&<><Text style={e.secao}>Certificados</Text>{certificados.map(c=><TouchableOpacity key={c.id} style={e.item} onPress={()=>nav.navigate('Certificados',{screen:'CertificadoDetalhe',params:{id:c.id}})}><View style={e.medal}><Text>🏅</Text></View><View style={{flex:1}}><Text style={e.itemT}>{c.numero}</Text><Text style={e.itemM}>Validade: {formatarData(c.dataValidade)}</Text></View><ChipStatus rotulo={c.status||'—'} tom={tom(c.status||'') as any}/></TouchableOpacity>)}</>}
</TelaBase></View>}
const e=StyleSheet.create({tela:{flex:1,backgroundColor:semantica.fundo},conteudo:{gap:espaco.md},perfil:{backgroundColor:semantica.fundoElevado,borderRadius:raio.grande,borderWidth:1,borderColor:semantica.borda,padding:espaco.md,flexDirection:'row',alignItems:'center',gap:espaco.md},nome:{...tipografia.titulo,color:semantica.texto},meta:{...tipografia.apoio,color:semantica.textoSecundario,marginTop:2},chips:{flexDirection:'row',alignItems:'center',gap:espaco.sm,marginTop:espaco.xs},chip:{...tipografia.apoio,fontSize:11,backgroundColor:cores.neve100,color:semantica.textoSecundario,paddingHorizontal:8,paddingVertical:4,borderRadius:raio.pilula},codigo:{...tipografia.codigo,fontSize:11,color:semantica.textoSecundario},grade:{flexDirection:'row',gap:espaco.sm},stat:{flex:1,backgroundColor:semantica.fundoElevado,borderRadius:raio.grande,borderWidth:1,borderColor:semantica.borda,padding:espaco.sm,alignItems:'center'},statN:{...tipografia.titulo,color:semantica.texto},statL:{...tipografia.apoio,fontSize:10,color:semantica.textoSecundario},secao:{...tipografia.subtitulo,fontSize:14,color:semantica.texto,marginTop:espaco.xs},item:{backgroundColor:semantica.fundoElevado,borderRadius:raio.grande,borderWidth:1,borderColor:semantica.borda,padding:espaco.sm,flexDirection:'row',alignItems:'center',gap:espaco.sm},itemT:{...tipografia.subtitulo,fontSize:13,color:semantica.texto},itemM:{...tipografia.apoio,fontSize:11,color:semantica.textoSecundario,marginTop:2},medal:{width:34,height:34,borderRadius:raio.medio,backgroundColor:cores.atencaoSuave,alignItems:'center',justifyContent:'center'}});
